//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnOOP_QuanLyKho.Model
{
    using DoAnOOP_QuanLyKho.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhap : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietPhieuNhap()
        {
            this.ChiTietPhieuXuats = new HashSet<ChiTietPhieuXuat>();
        }
    
        public int MaCTPNhap { get; set; }
        public int MaPN { get; set; }
        public int MaSP { get; set; }

        private int _SoLuongNhap;
        public int SoLuongNhap { get => _SoLuongNhap; set { _SoLuongNhap = value; OnPropertyChanged(); } }

        private decimal _DonGiaNhap;
        public decimal DonGiaNhap { get => _DonGiaNhap; set { _DonGiaNhap = value; OnPropertyChanged(); } }

        private decimal _DonGiaXuat;
        public decimal DonGiaXuat { get => _DonGiaXuat; set { _DonGiaXuat = value; OnPropertyChanged(); } }

        private decimal _GiaSanPham;
        public decimal GiaSanPham { get => _GiaSanPham; set { _GiaSanPham = value; OnPropertyChanged(); } }

        private System.DateTime _HSD;
        public System.DateTime HSD { get => _HSD; set { _HSD = value; OnPropertyChanged(); } }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuXuat> ChiTietPhieuXuats { get; set; }

        private PhieuNhap _PhieuNhap;
        public virtual PhieuNhap PhieuNhap { get => _PhieuNhap; set { _PhieuNhap = value; OnPropertyChanged(); } }

        private SanPham _SanPham;
        public virtual SanPham SanPham { get => _SanPham; set { _SanPham = value; OnPropertyChanged(); } }
    }
}
