//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnOOP_QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuXuat
    {
        public int MaCTPXuat { get; set; }
        public int MaCTPNhap { get; set; }
        public int MaPX { get; set; }
        public int MaSP { get; set; }
        public int SLXuat { get; set; }
    
        public virtual ChiTietPhieuNhap ChiTietPhieuNhap { get; set; }
        public virtual PhieuXuat PhieuXuat { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
